### ISSUE TITLE
output issues

### ISSUE THREAD

**Issue by cangokalp** [spartalab/tap-b#10]
flows.txt sometimes not generated, even though the full_log.txt is generated as an output.

**Comment by pyrito** [comment]
Can you give some more detail about this? I'm looking at the code and this method is called whenever the flows.txt needs to be outputted: writeNetworkFlows(). This is always called after finishing a run of TAP. Is the binary ending prematurely potentially?

**Comment by pyrito** [comment]
Closing this if the problem isn't an issue anymore - let me know if it is
