### ISSUE TITLE
flow.txt sometimes outputs dummy links

### ISSUE THREAD

**Issue by cangokalp** [spartalab/tap-b#7]
this file sometimes outputs dummy links that does not exists in the original network

**Comment by cangokalp** [comment]
this file sometimes outputs dummy links that does not exists in the original network

<img width="305" alt="Screen Shot 2020-06-16 at 4 11 19 PM" src="https://user-images.githubusercontent.com/11825301/85174207-86f0d980-b23a-11ea-8244-9e21720edc72.png">

this is from Anaheim network^

**Comment by ribsthakkar** [comment]
Fixed
