### ISSUE TITLE
output full_log.txt - weird output

### ISSUE THREAD

**Issue by cangokalp** [spartalab/tap-b#8]
example:

<img width="582" alt="Screen Shot 2020-06-18 at 12 53 46 PM" src="https://user-images.githubusercontent.com/11825301/85174138-5c9f1c00-b23a-11ea-81c1-86a6d50b71e7.png">

expected output should end after the iteration logs

**Comment by cangokalp** [comment]
expected output should end after the iteration logs

**Comment by pyrito** [comment]
Are you running the code in a default mode or did you use a DEBUG binary?

**Comment by cangokalp** [comment]
default

**Comment by ribsthakkar** [comment]
that is happening because of the #3 bug that we are still discussing. It is the debug log

**Comment by ribsthakkar** [comment]
Addressed #3 after mreged.
