### ISSUE TITLE
Additional feature - convergence gap parameterized

### ISSUE THREAD

**Issue by cangokalp** [spartalab/tap-b#9]
Can the gap be a parameter? So that if someone wants to solve for different gap levels they wouldn't need to change it in the code and then build again.

**Comment by pyrito** [comment]
Yes we are working on this, should have a PR in soon enough.

**Comment by pyrito** [comment]
@cangokalp if you want this right now, use the "cli-gap" branch.

**Comment by cangokalp** [comment]
ok thanks!

**Comment by ribsthakkar** [comment]
PR is up #13

**Comment by pyrito** [comment]
Merged in the main code
